{
  "hash": "ccc89d6d0fb4690cd0392d283f90265d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 4: Spatial Predictive Analysis\"\nsubtitle: \"Bias in Burglary Prediction Modeling\"\nauthor: \"Ixchel Ramirez\"\ndate: \"2025-11-17\"\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n# Crime Analysis in Chicago\n\n## Introduction\nThis lab looks into the correlation between 311 calls about street lights being out and burglaries. Lighting is often connected to people's perceptions on safety, people choose to walk a certain way at night because there are more street lights which enable them to see. I wanted to see how this perception of safety connects to burglary calls.  \n\n\n\n\nAbove section loads in necessary packages to allow for functions to run, placing this at the beginning of the document helps it remain organized. \n\n\n## Chicago Spatial Data \n\n::: {.cell}\n\n```{.r .cell-code}\n# Load police districts (used for spatial cross-validation)\npoliceDistricts <- \n  st_read(\"https://data.cityofchicago.org/api/geospatial/24zt-jpfn?method=export&format=GeoJSON\") %>%\n  st_transform('ESRI:102271') %>%\n  dplyr::select(District = dist_num)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `OGRGeoJSON' from data source \n  `https://data.cityofchicago.org/api/geospatial/24zt-jpfn?method=export&format=GeoJSON' \n  using driver `GeoJSON'\nSimple feature collection with 25 features and 2 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -87.94011 ymin: 41.64455 xmax: -87.52414 ymax: 42.02303\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n# Load police beats (smaller administrative units)\npoliceBeats <- \n  st_read(\"https://data.cityofchicago.org/api/geospatial/n9it-hstw?method=export&format=GeoJSON\") %>%\n  st_transform('ESRI:102271') %>%\n  dplyr::select(Beat = beat_num)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `OGRGeoJSON' from data source \n  `https://data.cityofchicago.org/api/geospatial/n9it-hstw?method=export&format=GeoJSON' \n  using driver `GeoJSON'\nSimple feature collection with 277 features and 4 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -87.94011 ymin: 41.64455 xmax: -87.52414 ymax: 42.02303\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n# Load Chicago boundary\nchicagoBoundary <- \n  st_read(\"https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/Chapter5/chicagoBoundary.geojson\") %>%\n  st_transform('ESRI:102271')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `chicagoBoundary' from data source \n  `https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/Chapter5/chicagoBoundary.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 1 feature and 1 field\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: -87.8367 ymin: 41.64454 xmax: -87.52414 ymax: 42.02304\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"✓ Loaded spatial boundaries\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Loaded spatial boundaries\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Police districts:\", nrow(policeDistricts), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Police districts: 25 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Police beats:\", nrow(policeBeats), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Police beats: 277 \n```\n\n\n:::\n:::\n\n\n##Loaded in Chicago Spatial data \nThe coordinate reference system is set to 'ESRI:102271' (Illinois State Plane East) because it minimizes distortion since all the data we are looking at is in Chicago. Additionally, since Chicago is in the US which feet as a system of measurement it removes the need to convert units and minimizes confusion and error in distance calculations.\n\n## Burglary Data\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load from provided data file (downloaded from Chicago open data portal)\n\nburglaries <- st_read(here(\"data\", \"burglaries.shp\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `burglaries' from data source \n  `C:\\Users\\ixche\\Desktop\\PPA\\portfolio-setup-ixchelramirez\\labs\\lab_4\\data\\burglaries.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 7482 features and 22 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 340492 ymin: 552959.6 xmax: 367153.5 ymax: 594815.1\nProjected CRS: NAD83(HARN) / Illinois East\n```\n\n\n:::\n\n```{.r .cell-code}\nburglaries <- st_transform(burglaries, crs = 'ESRI:102271')\n\n\n# Check the data\ncat(\"\\n✓ Loaded burglary data\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n✓ Loaded burglary data\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Number of burglaries:\", nrow(burglaries), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Number of burglaries: 7482 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - CRS:\", st_crs(burglaries)$input, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - CRS: ESRI:102271 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Date range:\", min(burglaries$date, na.rm = TRUE), \"to\", \n    max(burglaries$date, na.rm = TRUE), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Date range: Inf to -Inf \n```\n\n\n:::\n:::\n\nThere are 7482 burglaries in the data set and the CRS is also set to Chicago which is useful for later calculations that check distance. If the datasets used different coordinate reference systems then problems would arise later when calculating distance. It is important to understand that while there are 7482 burglaries the spatial distribution of these is likely unequal and reflects where crime is surveilled rather than only where crime occurs. \n\n## Visualize point data\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simple point map\np1 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"gray95\", color = \"gray60\") +\n  geom_sf(data = burglaries, color = \"#d62828\", size = 0.1, alpha = 0.4) +\n  labs(\n    title = \"Burglary Locations\",\n    subtitle = paste0(\"Chicago 2017, n = \", nrow(burglaries))\n  )\n\n# Density surface using modern syntax\np2 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"gray95\", color = \"gray60\") +\n  geom_density_2d_filled(\n    data = data.frame(st_coordinates(burglaries)),\n    aes(X, Y),\n    alpha = 0.7,\n    bins = 8\n  ) +\n  scale_fill_viridis_d(\n    option = \"plasma\",\n    direction = -1,\n    guide = \"none\"  # Modern ggplot2 syntax (not guide = FALSE)\n  ) +\n  labs(\n    title = \"Density Surface\",\n    subtitle = \"Kernel density estimation\"\n  )\n\n# Combine plots using patchwork (modern approach)\np1 + p2 + \n  plot_annotation(\n    title = \"Spatial Distribution of Burglaries in Chicago\",\n    tag_levels = 'A'\n  )\n```\n\n::: {.cell-output-display}\n![](Lab4_IxchelRamirez_files/figure-html/visualize point data-1.png){width=672}\n:::\n:::\n\n\n\nBurglaries are not evenly distributed across Chicago, they are more frequent on the South Side of Chicago. There is also a high concentration on the Northeast side. The South Side of Chicago has a reputation for being dangerous which could result in an increased police presense as well as an increase in willingness to report the crimes here. \n\n## Create the Fishnet\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create 500m x 500m grid\nfishnet <- st_make_grid(\n  chicagoBoundary,\n  cellsize = 500,  # 500 meters per cell\n  square = TRUE\n) %>%\n  st_sf() %>%\n  mutate(uniqueID = row_number())\n\n# Keep only cells that intersect Chicago\nfishnet <- fishnet[chicagoBoundary, ]\n\n# View basic info\ncat(\"✓ Created fishnet grid\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Created fishnet grid\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Number of cells:\", nrow(fishnet), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Number of cells: 2458 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Cell size:\", 500, \"x\", 500, \"meters\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Cell size: 500 x 500 meters\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Cell area:\", round(st_area(fishnet[1,])), \"square meters\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Cell area: 250000 square meters\n```\n\n\n:::\n:::\n\nThe step above creates a fishnet grid which turns the point data into a grid of cells. Creating a grid provides a uniform unit of analysis so that one can aggregate counts, calculate spatial features and run regression models. Existing boundaries like neighborhoods and census tracts change which could result an added step when comparing years. Neighborhood boundaries are particularly harder to use because not everyone agrees on where a neighborhood begins and ends. While this approach helps with standardization it is harder to understand where burglaries occur (such as which neighborhood) because the grid does not delineate this. Thus, it requires a degree of familiarity with the area and where neighborhoods are to understand how social interactions influence the observations from the data. \n\n## Aggregate Burglaries to Grid\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join: which cell contains each burglary?\nburglaries_fishnet <- st_join(burglaries, fishnet, join = st_within) %>%\n  st_drop_geometry() %>%\n  group_by(uniqueID) %>%\n  summarize(countBurglaries = n())\n\n# Join back to fishnet (cells with 0 burglaries will be NA)\nfishnet <- fishnet %>%\n  left_join(burglaries_fishnet, by = \"uniqueID\") %>%\n  mutate(countBurglaries = replace_na(countBurglaries, 0))\n\n# Summary statistics\ncat(\"\\nBurglary count distribution:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nBurglary count distribution:\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fishnet$countBurglaries)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  0.000   0.000   2.000   3.042   5.000  40.000 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nCells with zero burglaries:\", \n    sum(fishnet$countBurglaries == 0), \n    \"/\", nrow(fishnet),\n    \"(\", round(100 * sum(fishnet$countBurglaries == 0) / nrow(fishnet), 1), \"%)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCells with zero burglaries: 781 / 2458 ( 31.8 %)\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Visualize aggregated counts\nggplot() +\n  geom_sf(data = fishnet, aes(fill = countBurglaries), color = NA) +\n  geom_sf(data = chicagoBoundary, fill = NA, color = \"white\", linewidth = 1) +\n  scale_fill_viridis_c(\n    name = \"Burglaries\",\n    option = \"plasma\",\n    trans = \"sqrt\",  # Square root for better visualization of skewed data\n    breaks = c(0, 1, 5, 10, 20, 40)\n  ) +\n  labs(\n    title = \"Burglary Counts by Grid Cell\",\n    subtitle = \"500m x 500m cells, Chicago 2017\"\n  ) +\n  theme_crime()\n```\n\n::: {.cell-output-display}\n![](Lab4_IxchelRamirez_files/figure-html/visualize-fishnet-1.png){width=768}\n:::\n:::\n\n\nBurglaries are more dispersed in the South Side and in the core of the North. The largest cluster of cells with zero burglaries is also on the South Side. \n\n\n## Kernal Density Basemap\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert burglaries to ppp (point pattern) format for spatstat\nburglaries_ppp <- as.ppp(\n  st_coordinates(burglaries),\n  W = as.owin(st_bbox(chicagoBoundary))\n)\n\n# Calculate KDE with 1km bandwidth\nkde_burglaries <- density.ppp(\n  burglaries_ppp,\n  sigma = 1000,  # 1km bandwidth\n  edge = TRUE    # Edge correction\n)\n\n# Convert to terra raster (modern approach, not raster::raster)\nkde_raster <- rast(kde_burglaries)\n\n# Extract KDE values to fishnet cells\nfishnet <- fishnet %>%\n  mutate(\n    kde_value = terra::extract(\n      kde_raster,\n      vect(fishnet),\n      fun = mean,\n      na.rm = TRUE\n    )[, 2]  # Extract just the values column\n  )\n\ncat(\"✓ Calculated KDE baseline\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Calculated KDE baseline\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_sf(data = fishnet, aes(fill = kde_value), color = NA) +\n  geom_sf(data = chicagoBoundary, fill = NA, color = \"white\", linewidth = 1) +\n  scale_fill_viridis_c(\n    name = \"KDE Value\",\n    option = \"plasma\"\n  ) +\n  labs(\n    title = \"Kernel Density Estimation Baseline\",\n    subtitle = \"Simple spatial smoothing of burglary locations\"\n  ) +\n  theme_crime()\n```\n\n::: {.cell-output-display}\n![](Lab4_IxchelRamirez_files/figure-html/visualize-kde-1.png){width=768}\n:::\n:::\n\n\n\nThe above map looks very similar to the other patterns of crime in Chicago because a KDE baseline looks as what happens if an incident, in this case burglaries happens where they did before. This map counts the clusters of incidents well.\n\n## Spatial predictor variables\n\n::: {.cell}\n\n```{.r .cell-code}\nstreetLights_allOut <- read_csv(here(\"data/311_Service_Requests_-_Street_Lights_-_All_Out_-_Historical_20251112.csv\"))%>%\n  filter(!is.na(Latitude), !is.na(Longitude)) %>%\n  st_as_sf(coords = c(\"Longitude\", \"Latitude\"), crs = 4326) %>%\n  st_transform('ESRI:102271')\n\n#cat(\"✓ Loaded street vehicle calls\\n\")\ncat(\"  - Number of calls:\", nrow(streetLights_allOut), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Number of calls: 296511 \n```\n\n\n:::\n\n```{.r .cell-code}\n\"data/311_Service_Requests_-_Street_Lights_-_All_Out_-_Historical_20251112.csv\"\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"data/311_Service_Requests_-_Street_Lights_-_All_Out_-_Historical_20251112.csv\"\n```\n\n\n:::\n:::\n\n\n\n## Count of Street Lights all out per cell\n\n::: {.cell}\n\n```{.r .cell-code}\n# Aggregate lights out to fishnet\nlights_fishnet <- st_join(streetLights_allOut, fishnet, join = st_within) %>%\n  st_drop_geometry() %>%\n  group_by(uniqueID) %>%\n  summarize(streetLights_allOut = n())\n\n# Join to fishnet\nfishnet <- fishnet %>%\n  left_join(lights_fishnet, by = \"uniqueID\") %>%\n  mutate(streetLights_allOut = replace_na(streetLights_allOut, 0))\n\ncat(\"All lights out distribution:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAll lights out distribution:\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fishnet$streetLights_allOut)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n    0.0    38.0   102.0   120.4   175.8   706.0 \n```\n\n\n:::\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = streetLights_allOut), color = NA) +\n  scale_fill_viridis_c(name = \"Count\", option = \"magma\") +\n  labs(title = \"All Lights Out 311 Calls\") +\n  theme_crime()\n\np2 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = countBurglaries), color = NA) +\n  scale_fill_viridis_c(name = \"Count\", option = \"plasma\") +\n  labs(title = \"Burglaries\") +\n  theme_crime()\n\np1 + p2 +\n  plot_annotation(title = \"Are street lights out and burglaries correlated?\")\n```\n\n::: {.cell-output-display}\n![](Lab4_IxchelRamirez_files/figure-html/visualize-streetlights-allout-1.png){width=960}\n:::\n:::\n\n\n\nIn this section I pulled data from Chicago's Open Data portal for 311 calls on street lights that are all out. Visually there are similarities between where burglairies occur and where street lights are all out specifically on the South Side there is more difference between these two categories in the North. This suggests that where street lights are out could help predict burglaries, but more likely just implies perceptions of safety.\n\n## Nearest Neighbor \n\nHere we are calculating the mean distance to the 3 nearest blockw with all the lights out. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate mean distance to 3 nearest lights out\n# (Do this OUTSIDE of mutate to avoid sf conflicts)\n\n# Get coordinates\nfishnet_coords <- st_coordinates(st_centroid(fishnet))\nlights_coords <- st_coordinates(streetLights_allOut)\n\n# Calculate k nearest neighbors and distances\nnn_result <- get.knnx(lights_coords, fishnet_coords, k = 3)\n\n# Add to fishnet\nfishnet <- fishnet %>%\n  mutate(\n    streetLights_allOut.nn = rowMeans(nn_result$nn.dist)\n  )\n\ncat(\"✓ Calculated nearest neighbor distances\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Calculated nearest neighbor distances\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fishnet$streetLights_allOut.nn)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. \n   0.9959   38.0172   59.4470  119.7214  110.8656 1436.3413 \n```\n\n\n:::\n:::\n\n\n\nA low value of streetLights_allOut.nn means means that the block is closer to other blocks with the lights out while a high value means that a cell is far from other cells with blocks that have the lights out. Blocks that have low value could indicate decreasing perceptions of safety. \n\n\n## Distance to Hot Spots\n\n::: {.cell}\n\n```{.r .cell-code}\n#used this for local_moran becuase when it saves fishnet as fishnet it aborts 2. dplyr mutate + sf can still corrupt the geometry column\n\ncoords <- st_coordinates(st_centroid(fishnet))\nneighbors <- knn2nb(knearneigh(coords, k = 5))\nweights <- nb2listw(neighbors, style = \"W\", zero.policy = TRUE)\n\nlocal_moran <- localmoran(fishnet[[\"streetLights_allOut\"]], weights)\nmean_val <- mean(fishnet[[\"streetLights_allOut\"]], na.rm = TRUE)\n\nfishnet$local_i <- local_moran[,1]\nfishnet$p_value <- local_moran[,5]\nfishnet$is_significant <- fishnet$p_value < 0.05\n\nmean_val <- mean(fishnet$streetLights_allOut, na.rm = TRUE)\n\nfishnet$moran_class <- dplyr::case_when(\n  !fishnet$is_significant ~ \"Not Significant\",\n  fishnet$local_i > 0 & fishnet$streetLights_allOut > mean_val ~ \"High-High\",\n  fishnet$local_i > 0 & fishnet$streetLights_allOut <= mean_val ~ \"Low-Low\",\n  fishnet$local_i < 0 & fishnet$streetLights_allOut > mean_val ~ \"High-Low\",\n  fishnet$local_i < 0 & fishnet$streetLights_allOut <= mean_val ~ \"Low-High\"\n)\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Visualize hot spots\nggplot() +\n  geom_sf(\n    data = fishnet, \n    aes(fill = moran_class), \n    color = NA\n  ) +\n  scale_fill_manual(\n    values = c(\n      \"High-High\" = \"#d7191c\",\n      \"High-Low\" = \"#fdae61\",\n      \"Low-High\" = \"#abd9e9\",\n      \"Low-Low\" = \"#2c7bb6\",\n      \"Not Significant\" = \"gray90\"\n    ),\n    name = \"Cluster Type\"\n  ) +\n  labs(\n    title = \"Local Moran's I: Lights Out Clusters\",\n    subtitle = \"High-High = Hot spots of disorder\"\n  ) +\n  theme_crime()\n```\n\n::: {.cell-output-display}\n![](Lab4_IxchelRamirez_files/figure-html/visualize-morans-1.png){width=768}\n:::\n\n```{.r .cell-code}\n#fill= moran_class is not running \n```\n:::\n\n\nThe distance to a cluster of lights that are out are helpful because it shows local spatial density while only looking at the distance to one specific point could be a random incident. From the distribution there are no areas with a high-low distribution and few areas with a low-high distribution. Low-low distributions, which are cold spots few lights are out and next to people without lights out, are clustered in the Southeast corner of Chicago, with patches around the boundary of the city. This means there are low values and its surrounded by other low values. High-high clusters are in the center of Chicago suggests that the observations are part of a cluster of high values and surrounded by high values i.e. street light blocks are out and they are next to other areas with street lights that are out. One thing to keep in mind is that the boundaries of Chicago have fewer neighbors thus this could bias the results and result with the spatial outliers such as high-low results. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get centroids of \"High-High\" cells (hot spots)\nhotspots <- fishnet %>%\n  filter(moran_class == \"High-High\") %>%\n  st_centroid()\n\n# Calculate distance from each cell to nearest hot spot\nif (nrow(hotspots) > 0) {\n  fishnet <- fishnet %>%\n    mutate(\n      dist_to_hotspot = as.numeric(\n        st_distance(st_centroid(fishnet), hotspots %>% st_union())\n      )\n    )\n  \n  cat(\"✓ Calculated distance to abandoned car hot spots\\n\")\n  cat(\"  - Number of hot spot cells:\", nrow(hotspots), \"\\n\")\n} else {\n  fishnet <- fishnet %>%\n    mutate(dist_to_hotspot = 0)\n  cat(\"⚠ No significant hot spots found\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Calculated distance to abandoned car hot spots\n  - Number of hot spot cells: 297 \n```\n\n\n:::\n:::\n\nThere are 297 hot spots.\n\n\n## Cross Validation \n\n::: {.cell}\n\n```{.r .cell-code}\n# Join district information to fishnet\nfishnet <- st_join(\n  fishnet,\n  policeDistricts,\n  join = st_within,\n  left = TRUE\n) %>%\n  filter(!is.na(District))  # Remove cells outside districts\n\ncat(\"✓ Joined police districts\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Joined police districts\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Districts:\", length(unique(fishnet$District)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Districts: 22 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Cells:\", nrow(fishnet), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Cells: 1708 \n```\n\n\n:::\n:::\n\nPolice districts are used for the spatial cross-validation because we are using crime data.\n\n\n## Poisson Regression\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create clean modeling dataset\nfishnet_model <- fishnet %>%\n  st_drop_geometry() %>%\n  dplyr::select(\n    uniqueID,\n    District,\n    countBurglaries,\n    streetLights_allOut,\n    streetLights_allOut.nn,\n    dist_to_hotspot\n  ) %>%\n  na.omit()  # Remove any remaining NAs\n\ncat(\"✓ Prepared modeling data\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Prepared modeling data\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Observations:\", nrow(fishnet_model), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Observations: 1708 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  - Variables:\", ncol(fishnet_model), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Variables: 6 \n```\n\n\n:::\n:::\n\nThere are 1708 observations and 6 variables. All of the values are positive because we are counting and cannot have a negative number.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfishnet_safe <- data.frame(\n  countBurglaries      = as.numeric(fishnet_model$countBurglaries),\n  streetLights_allOut  = as.numeric(fishnet_model$streetLights_allOut),\n  streetLights_allOut.nn = as.numeric(fishnet_model$streetLights_allOut.nn),\n  dist_to_hotspot      = as.numeric(fishnet_model$dist_to_hotspot)\n)\n\n# Remove row.names just in case\nrownames(fishnet_safe) <- NULL\n\n# Confirm attributes might not need attributes through glm just need to write.csv so could delete\nattributes(fishnet_safe)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$names\n[1] \"countBurglaries\"        \"streetLights_allOut\"    \"streetLights_allOut.nn\"\n[4] \"dist_to_hotspot\"       \n\n$class\n[1] \"data.frame\"\n\n$row.names\n   [1]    1    2    3    4    5    6    7    8    9   10   11   12   13   14\n  [15]   15   16   17   18   19   20   21   22   23   24   25   26   27   28\n  [29]   29   30   31   32   33   34   35   36   37   38   39   40   41   42\n  [43]   43   44   45   46   47   48   49   50   51   52   53   54   55   56\n  [57]   57   58   59   60   61   62   63   64   65   66   67   68   69   70\n  [71]   71   72   73   74   75   76   77   78   79   80   81   82   83   84\n  [85]   85   86   87   88   89   90   91   92   93   94   95   96   97   98\n  [99]   99  100  101  102  103  104  105  106  107  108  109  110  111  112\n [113]  113  114  115  116  117  118  119  120  121  122  123  124  125  126\n [127]  127  128  129  130  131  132  133  134  135  136  137  138  139  140\n [141]  141  142  143  144  145  146  147  148  149  150  151  152  153  154\n [155]  155  156  157  158  159  160  161  162  163  164  165  166  167  168\n [169]  169  170  171  172  173  174  175  176  177  178  179  180  181  182\n [183]  183  184  185  186  187  188  189  190  191  192  193  194  195  196\n [197]  197  198  199  200  201  202  203  204  205  206  207  208  209  210\n [211]  211  212  213  214  215  216  217  218  219  220  221  222  223  224\n [225]  225  226  227  228  229  230  231  232  233  234  235  236  237  238\n [239]  239  240  241  242  243  244  245  246  247  248  249  250  251  252\n [253]  253  254  255  256  257  258  259  260  261  262  263  264  265  266\n [267]  267  268  269  270  271  272  273  274  275  276  277  278  279  280\n [281]  281  282  283  284  285  286  287  288  289  290  291  292  293  294\n [295]  295  296  297  298  299  300  301  302  303  304  305  306  307  308\n [309]  309  310  311  312  313  314  315  316  317  318  319  320  321  322\n [323]  323  324  325  326  327  328  329  330  331  332  333  334  335  336\n [337]  337  338  339  340  341  342  343  344  345  346  347  348  349  350\n [351]  351  352  353  354  355  356  357  358  359  360  361  362  363  364\n [365]  365  366  367  368  369  370  371  372  373  374  375  376  377  378\n [379]  379  380  381  382  383  384  385  386  387  388  389  390  391  392\n [393]  393  394  395  396  397  398  399  400  401  402  403  404  405  406\n [407]  407  408  409  410  411  412  413  414  415  416  417  418  419  420\n [421]  421  422  423  424  425  426  427  428  429  430  431  432  433  434\n [435]  435  436  437  438  439  440  441  442  443  444  445  446  447  448\n [449]  449  450  451  452  453  454  455  456  457  458  459  460  461  462\n [463]  463  464  465  466  467  468  469  470  471  472  473  474  475  476\n [477]  477  478  479  480  481  482  483  484  485  486  487  488  489  490\n [491]  491  492  493  494  495  496  497  498  499  500  501  502  503  504\n [505]  505  506  507  508  509  510  511  512  513  514  515  516  517  518\n [519]  519  520  521  522  523  524  525  526  527  528  529  530  531  532\n [533]  533  534  535  536  537  538  539  540  541  542  543  544  545  546\n [547]  547  548  549  550  551  552  553  554  555  556  557  558  559  560\n [561]  561  562  563  564  565  566  567  568  569  570  571  572  573  574\n [575]  575  576  577  578  579  580  581  582  583  584  585  586  587  588\n [589]  589  590  591  592  593  594  595  596  597  598  599  600  601  602\n [603]  603  604  605  606  607  608  609  610  611  612  613  614  615  616\n [617]  617  618  619  620  621  622  623  624  625  626  627  628  629  630\n [631]  631  632  633  634  635  636  637  638  639  640  641  642  643  644\n [645]  645  646  647  648  649  650  651  652  653  654  655  656  657  658\n [659]  659  660  661  662  663  664  665  666  667  668  669  670  671  672\n [673]  673  674  675  676  677  678  679  680  681  682  683  684  685  686\n [687]  687  688  689  690  691  692  693  694  695  696  697  698  699  700\n [701]  701  702  703  704  705  706  707  708  709  710  711  712  713  714\n [715]  715  716  717  718  719  720  721  722  723  724  725  726  727  728\n [729]  729  730  731  732  733  734  735  736  737  738  739  740  741  742\n [743]  743  744  745  746  747  748  749  750  751  752  753  754  755  756\n [757]  757  758  759  760  761  762  763  764  765  766  767  768  769  770\n [771]  771  772  773  774  775  776  777  778  779  780  781  782  783  784\n [785]  785  786  787  788  789  790  791  792  793  794  795  796  797  798\n [799]  799  800  801  802  803  804  805  806  807  808  809  810  811  812\n [813]  813  814  815  816  817  818  819  820  821  822  823  824  825  826\n [827]  827  828  829  830  831  832  833  834  835  836  837  838  839  840\n [841]  841  842  843  844  845  846  847  848  849  850  851  852  853  854\n [855]  855  856  857  858  859  860  861  862  863  864  865  866  867  868\n [869]  869  870  871  872  873  874  875  876  877  878  879  880  881  882\n [883]  883  884  885  886  887  888  889  890  891  892  893  894  895  896\n [897]  897  898  899  900  901  902  903  904  905  906  907  908  909  910\n [911]  911  912  913  914  915  916  917  918  919  920  921  922  923  924\n [925]  925  926  927  928  929  930  931  932  933  934  935  936  937  938\n [939]  939  940  941  942  943  944  945  946  947  948  949  950  951  952\n [953]  953  954  955  956  957  958  959  960  961  962  963  964  965  966\n [967]  967  968  969  970  971  972  973  974  975  976  977  978  979  980\n [981]  981  982  983  984  985  986  987  988  989  990  991  992  993  994\n [995]  995  996  997  998  999 1000 1001 1002 1003 1004 1005 1006 1007 1008\n[1009] 1009 1010 1011 1012 1013 1014 1015 1016 1017 1018 1019 1020 1021 1022\n[1023] 1023 1024 1025 1026 1027 1028 1029 1030 1031 1032 1033 1034 1035 1036\n[1037] 1037 1038 1039 1040 1041 1042 1043 1044 1045 1046 1047 1048 1049 1050\n[1051] 1051 1052 1053 1054 1055 1056 1057 1058 1059 1060 1061 1062 1063 1064\n[1065] 1065 1066 1067 1068 1069 1070 1071 1072 1073 1074 1075 1076 1077 1078\n[1079] 1079 1080 1081 1082 1083 1084 1085 1086 1087 1088 1089 1090 1091 1092\n[1093] 1093 1094 1095 1096 1097 1098 1099 1100 1101 1102 1103 1104 1105 1106\n[1107] 1107 1108 1109 1110 1111 1112 1113 1114 1115 1116 1117 1118 1119 1120\n[1121] 1121 1122 1123 1124 1125 1126 1127 1128 1129 1130 1131 1132 1133 1134\n[1135] 1135 1136 1137 1138 1139 1140 1141 1142 1143 1144 1145 1146 1147 1148\n[1149] 1149 1150 1151 1152 1153 1154 1155 1156 1157 1158 1159 1160 1161 1162\n[1163] 1163 1164 1165 1166 1167 1168 1169 1170 1171 1172 1173 1174 1175 1176\n[1177] 1177 1178 1179 1180 1181 1182 1183 1184 1185 1186 1187 1188 1189 1190\n[1191] 1191 1192 1193 1194 1195 1196 1197 1198 1199 1200 1201 1202 1203 1204\n[1205] 1205 1206 1207 1208 1209 1210 1211 1212 1213 1214 1215 1216 1217 1218\n[1219] 1219 1220 1221 1222 1223 1224 1225 1226 1227 1228 1229 1230 1231 1232\n[1233] 1233 1234 1235 1236 1237 1238 1239 1240 1241 1242 1243 1244 1245 1246\n[1247] 1247 1248 1249 1250 1251 1252 1253 1254 1255 1256 1257 1258 1259 1260\n[1261] 1261 1262 1263 1264 1265 1266 1267 1268 1269 1270 1271 1272 1273 1274\n[1275] 1275 1276 1277 1278 1279 1280 1281 1282 1283 1284 1285 1286 1287 1288\n[1289] 1289 1290 1291 1292 1293 1294 1295 1296 1297 1298 1299 1300 1301 1302\n[1303] 1303 1304 1305 1306 1307 1308 1309 1310 1311 1312 1313 1314 1315 1316\n[1317] 1317 1318 1319 1320 1321 1322 1323 1324 1325 1326 1327 1328 1329 1330\n[1331] 1331 1332 1333 1334 1335 1336 1337 1338 1339 1340 1341 1342 1343 1344\n[1345] 1345 1346 1347 1348 1349 1350 1351 1352 1353 1354 1355 1356 1357 1358\n[1359] 1359 1360 1361 1362 1363 1364 1365 1366 1367 1368 1369 1370 1371 1372\n[1373] 1373 1374 1375 1376 1377 1378 1379 1380 1381 1382 1383 1384 1385 1386\n[1387] 1387 1388 1389 1390 1391 1392 1393 1394 1395 1396 1397 1398 1399 1400\n[1401] 1401 1402 1403 1404 1405 1406 1407 1408 1409 1410 1411 1412 1413 1414\n[1415] 1415 1416 1417 1418 1419 1420 1421 1422 1423 1424 1425 1426 1427 1428\n[1429] 1429 1430 1431 1432 1433 1434 1435 1436 1437 1438 1439 1440 1441 1442\n[1443] 1443 1444 1445 1446 1447 1448 1449 1450 1451 1452 1453 1454 1455 1456\n[1457] 1457 1458 1459 1460 1461 1462 1463 1464 1465 1466 1467 1468 1469 1470\n[1471] 1471 1472 1473 1474 1475 1476 1477 1478 1479 1480 1481 1482 1483 1484\n[1485] 1485 1486 1487 1488 1489 1490 1491 1492 1493 1494 1495 1496 1497 1498\n[1499] 1499 1500 1501 1502 1503 1504 1505 1506 1507 1508 1509 1510 1511 1512\n[1513] 1513 1514 1515 1516 1517 1518 1519 1520 1521 1522 1523 1524 1525 1526\n[1527] 1527 1528 1529 1530 1531 1532 1533 1534 1535 1536 1537 1538 1539 1540\n[1541] 1541 1542 1543 1544 1545 1546 1547 1548 1549 1550 1551 1552 1553 1554\n[1555] 1555 1556 1557 1558 1559 1560 1561 1562 1563 1564 1565 1566 1567 1568\n[1569] 1569 1570 1571 1572 1573 1574 1575 1576 1577 1578 1579 1580 1581 1582\n[1583] 1583 1584 1585 1586 1587 1588 1589 1590 1591 1592 1593 1594 1595 1596\n[1597] 1597 1598 1599 1600 1601 1602 1603 1604 1605 1606 1607 1608 1609 1610\n[1611] 1611 1612 1613 1614 1615 1616 1617 1618 1619 1620 1621 1622 1623 1624\n[1625] 1625 1626 1627 1628 1629 1630 1631 1632 1633 1634 1635 1636 1637 1638\n[1639] 1639 1640 1641 1642 1643 1644 1645 1646 1647 1648 1649 1650 1651 1652\n[1653] 1653 1654 1655 1656 1657 1658 1659 1660 1661 1662 1663 1664 1665 1666\n[1667] 1667 1668 1669 1670 1671 1672 1673 1674 1675 1676 1677 1678 1679 1680\n[1681] 1681 1682 1683 1684 1685 1686 1687 1688 1689 1690 1691 1692 1693 1694\n[1695] 1695 1696 1697 1698 1699 1700 1701 1702 1703 1704 1705 1706 1707 1708\n```\n\n\n:::\n\n```{.r .cell-code}\nglm(countBurglaries ~ streetLights_allOut, data = fishnet_safe, family = poisson())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:  glm(formula = countBurglaries ~ streetLights_allOut, family = poisson(), \n    data = fishnet_safe)\n\nCoefficients:\n        (Intercept)  streetLights_allOut  \n           0.670548             0.003695  \n\nDegrees of Freedom: 1707 Total (i.e. Null);  1706 Residual\nNull Deviance:\t    6710 \nResidual Deviance: 5545 \tAIC: 9609\n```\n\n\n:::\n\n```{.r .cell-code}\nglm(countBurglaries ~ streetLights_allOut.nn, data = fishnet_safe, family = poisson())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:  glm(formula = countBurglaries ~ streetLights_allOut.nn, family = poisson(), \n    data = fishnet_safe)\n\nCoefficients:\n           (Intercept)  streetLights_allOut.nn  \n                1.8609                 -0.0099  \n\nDegrees of Freedom: 1707 Total (i.e. Null);  1706 Residual\nNull Deviance:\t    6710 \nResidual Deviance: 5286 \tAIC: 9350\n```\n\n\n:::\n\n```{.r .cell-code}\nglm(countBurglaries ~ dist_to_hotspot, data = fishnet_safe, family = poisson())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:  glm(formula = countBurglaries ~ dist_to_hotspot, family = poisson(), \n    data = fishnet_safe)\n\nCoefficients:\n    (Intercept)  dist_to_hotspot  \n      1.5780441       -0.0001758  \n\nDegrees of Freedom: 1707 Total (i.e. Null);  1706 Residual\nNull Deviance:\t    6710 \nResidual Deviance: 6165 \tAIC: 10230\n```\n\n\n:::\n\n```{.r .cell-code}\nglm(countBurglaries ~ streetLights_allOut + streetLights_allOut.nn + dist_to_hotspot,\n    data = fishnet_safe, family = poisson())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:  glm(formula = countBurglaries ~ streetLights_allOut + streetLights_allOut.nn + \n    dist_to_hotspot, family = poisson(), data = fishnet_safe)\n\nCoefficients:\n           (Intercept)     streetLights_allOut  streetLights_allOut.nn  \n            1.59385399              0.00176658             -0.00744121  \n       dist_to_hotspot  \n           -0.00008897  \n\nDegrees of Freedom: 1707 Total (i.e. Null);  1704 Residual\nNull Deviance:\t    6710 \nResidual Deviance: 4784 \tAIC: 8852\n```\n\n\n:::\n\n```{.r .cell-code}\nwrite.csv(fishnet_safe, \"fishnet_safe.csv\", row.names = FALSE)\nfishnet_reload <- read.csv(\"fishnet_safe.csv\")\n\nglm(countBurglaries ~ streetLights_allOut + streetLights_allOut.nn + dist_to_hotspot,\n    data = fishnet_reload, family = poisson())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:  glm(formula = countBurglaries ~ streetLights_allOut + streetLights_allOut.nn + \n    dist_to_hotspot, family = poisson(), data = fishnet_reload)\n\nCoefficients:\n           (Intercept)     streetLights_allOut  streetLights_allOut.nn  \n            1.59385399              0.00176658             -0.00744121  \n       dist_to_hotspot  \n           -0.00008897  \n\nDegrees of Freedom: 1707 Total (i.e. Null);  1704 Residual\nNull Deviance:\t    6710 \nResidual Deviance: 4784 \tAIC: 8852\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(speedglm)\n\n\nmodel_poisson <- speedglm(\n  countBurglaries ~ streetLights_allOut + streetLights_allOut.nn + dist_to_hotspot,\n  data = fishnet_reload,\n  family = poisson()\n)\n\nsummary(model_poisson)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeneralized Linear Model of class 'speedglm':\n\nCall:  speedglm(formula = countBurglaries ~ streetLights_allOut + streetLights_allOut.nn +      dist_to_hotspot, data = fishnet_reload, family = poisson()) \n\nCoefficients:\n ------------------------------------------------------------------ \n                          Estimate  Std. Error z value\n(Intercept)             1.59385399 0.044790028   35.59\nstreetLights_allOut     0.00176658 0.000136858   12.91\nstreetLights_allOut.nn -0.00744121 0.000389666  -19.10\ndist_to_hotspot        -0.00008897 0.000008296  -10.72\n                                                                                                                                                                                                                                                                                                         Pr(>|z|)\n(Intercept)            0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002389\nstreetLights_allOut    0.0000000000000000000000000000000000000404971759840615121855966762609568831976503133773803710937500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\nstreetLights_allOut.nn 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000027054427954730279779968493691910680354340001940727233886718750000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\ndist_to_hotspot        0.0000000000000000000000000077723304606111821997947719520283271776861511170864105224609375000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\n                          \n(Intercept)            ***\nstreetLights_allOut    ***\nstreetLights_allOut.nn ***\ndist_to_hotspot        ***\n\n------------------------------------------------------------------- \nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 \n\n---\nnull df: 1707; null deviance: 6710.26;\nresiduals df: 1704; residuals deviance: 4784.14;\n# obs.: 1708; # non-zero weighted obs.: 1708;\nAIC: 8852.478; log Likelihood: -4422.239;\nRSS: 5285.5; dispersion: 1; iterations: 5;\nrank: 4; max tolerance: 8.18e-09; convergence: TRUE.\n```\n\n\n:::\n:::\n\n\nThe Poisson regression results indicate that burglary counts are significantly associated with street lighting conditions and proximity to known hotspots. Blocks with more streetlights out tend to experience slightly higher numbers of burglaries, while blocks that are farther from other lights-out blocks have lower expected burglary counts, suggesting that clusters of poorly lit areas are more vulnerable. Additionally, blocks located closer to established burglary hotspots are at greater risk. All three predictors—total street lights out (12.91), mean distance to other lights-out blocks (-19.1), and distance to hotspots (-10.72) are highly significant based on their values. The model shows that areas with less lighting are more likely to be near areas where more burglary is reported.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate dispersion parameter\ndf_resid <- nrow(fishnet_reload) - length(model_poisson$coefficients)\n\ndispersion <- model_poisson$deviance / df_resid\ndispersion\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.807592\n```\n\n\n:::\n\n```{.r .cell-code}\nif (dispersion > 1.5) {\n  cat(\"⚠ Overdispersion detected! Consider Negative Binomial model.\\n\")\n} else {\n  cat(\"✓ Dispersion looks okay for Poisson model.\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n⚠ Overdispersion detected! Consider Negative Binomial model.\n```\n\n\n:::\n:::\n\nOverdispersion is detected which means the variance of the response variable exceeds it's mean, which is an assumption in the Poisson distribution. \n\n## Negative Binomial Regression \n\n::: {.cell}\n\n```{.r .cell-code}\n##ALternative way to get negative binomial regression\n\n# Fit NB using Poisson coefficients as starting values\npoisson_coefs <- coef(glm(\n  countBurglaries ~ streetLights_allOut + streetLights_allOut.nn + dist_to_hotspot,\n  data = fishnet_reload,\n  family = poisson()\n))\n\nmodel_nb <- glm.nb(\n  countBurglaries ~ streetLights_allOut + streetLights_allOut.nn + dist_to_hotspot,\n  data = fishnet_reload,\n  init.theta = 1,               # initial theta\n  control = glm.control(maxit = 100, epsilon = 1e-8),\n  start = poisson_coefs         # start from Poisson estimates\n)\nsummary(model_nb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm.nb(formula = countBurglaries ~ streetLights_allOut + streetLights_allOut.nn + \n    dist_to_hotspot, data = fishnet_reload, start = poisson_coefs, \n    control = glm.control(maxit = 100, epsilon = 0.00000001), \n    init.theta = 1.743746675, link = log)\n\nCoefficients:\n                          Estimate  Std. Error z value             Pr(>|z|)    \n(Intercept)             1.57250588  0.08224961  19.119 < 0.0000000000000002 ***\nstreetLights_allOut     0.00218895  0.00027911   7.843  0.00000000000000441 ***\nstreetLights_allOut.nn -0.00888123  0.00061115 -14.532 < 0.0000000000000002 ***\ndist_to_hotspot        -0.00007061  0.00001352  -5.223  0.00000017591941882 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for Negative Binomial(1.7437) family taken to be 1)\n\n    Null deviance: 2647.3  on 1707  degrees of freedom\nResidual deviance: 1818.0  on 1704  degrees of freedom\nAIC: 7464.1\n\nNumber of Fisher Scoring iterations: 1\n\n              Theta:  1.744 \n          Std. Err.:  0.101 \n\n 2 x log-likelihood:  -7454.085 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nModel Comparison:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nModel Comparison:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Poisson AIC:\", round(AIC(model_poisson), 1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPoisson AIC: 8852.5 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Negative Binomial AIC:\", round(AIC(model_nb), 1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNegative Binomial AIC: 7464.1 \n```\n\n\n:::\n:::\n\n\nThe negative binomial regression results show that all three predictors are highly significant, which is consistent with the Poisson model. More streetlights out is associated with higher burglary counts, greater distance to other lights-out blocks is associated with fewer burglaries, and closer proximity to a hotspot increases burglary risk. The negative binomial model accounts for overdispersion in the data, which we saw above. \n\nLooking at the AIC, the Negative Binomial Model has a lower AIC, 7464.1, than the Poisson model, 8852.5, indicating that it provides a better fit for the data. The Negative Binomial Model having a better fit makes sense given that the assumption of equal mean and variance is violated for the Poisson model. This means the Negative Binomial Model is better at capturing burglary reports in Chicago.\n\n\nPart 5 and 6 could not be completed as I continued to run into an error in step 5. \n",
    "supporting": [
      "Lab4_IxchelRamirez_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}